import '@workspace/ui/globals.css';
import '@/app/globals.css';
import { Providers } from '@/components/providers';
import { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from '@/components/header/Header';
import Footer from '@/components/Footer';
import { Toaster } from '@workspace/ui/components';

const fonetika = localFont({
	src: [
		{ path: '../public/assets/fonts/Fonetika/Fonetika-Regular.otf', weight: '400', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/Fonetika-Medium.otf', weight: '500', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/Fonetika-SemiBold.otf', weight: '600', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/Fonetika-Bold.otf', weight: '700', style: 'normal' },
	],
	variable: '--font-fonetika',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning className="min-h-full w-full">
			<body className={`${fonetika.variable} antialiased h-full w-full flex flex-col`}>
				<Providers>
					<Header />
					{children}
					<Footer />
					<Toaster position="top-left" />
				</Providers>
			</body>
		</html>
	);
}
