import '@workspace/ui/globals.css';
import '@/app/globals.css';
import '@/app/loading.css';
import { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from '@/components/header/Header';
import Footer from '@/components/Footer';
import { Toaster } from '@workspace/ui/components';
import { SiteConfigProvider } from '@/components/providers/SiteConfigProvider';

const fonetika = localFont({
	src: [
		{ path: '../public/assets/fonts/Fonetika/FonetikaUnlicensedTrial-Regular.woff2', weight: '400', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/FonetikaUnlicensedTrial-Medium.woff2', weight: '500', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/FonetikaUnlicensedTrial-SemiBold.woff2', weight: '600', style: 'normal' },
		{ path: '../public/assets/fonts/Fonetika/FonetikaUnlicensedTrial-Bold.woff2', weight: '700', style: 'normal' },
	],
	variable: '--font-fonetika',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};



import { Suspense } from 'react';
import Loading from './loading';
import { NavigationLoadingProvider } from '@/components/providers/NavigationLoadingProvider';

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning className="flex flex-col min-h-full">
			<body className={`${fonetika.variable} antialiased flex-1 flex flex-col`}>
				<SiteConfigProvider>
					<NavigationLoadingProvider />
					<Header />
					<Suspense fallback={<Loading />}>
						{children}
					</Suspense>
					<Footer />
					<Toaster position="top-left" />
				</SiteConfigProvider>
			</body>
		</html>
	);
}
