import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fonetika = localFont({
  src: [
    {
      path: "../public/fonts/Fonetika/Fonetika-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Fonetika/Fonetika-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Fonetika/Fonetika-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Fonetika/Fonetika-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-fonetika",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonetika.variable} antialiased`}>{children}</body>
    </html>
  );
}
